version: "3"
services: 
    nginx: 
        image: nginx
        ports: 
            - 80:80
            - 443:443
        volumes: 
            - ./nginx/data:/data
            - ./nginx/cert:/cert
            - ./nginx/conf/expshare.conf:/etc/nginx/conf.d/default.conf
        privileged: true
        depends_on: 
            - gateway

    eureka: 
        image: java
        ports: 
            - 9001:9001
        volumes: 
            - ./eureka/app:/app
        command: 
            java -jar /app/expshare-eureka.jar --spring.profiles.active=prod && tail -f /etc/profile
        privileged: true

    gateway: 
        image: java
        ports: 
            - 9003:9003
        volumes:
            - ./gateway/app:/app
        command: 
            java -jar /app/expshare-gateway.jar --spring.profiles.active=prod && tail -f /etc/profile
        privileged: true
        depends_on: 
            - eureka
            - business

    business: 
        build: ./business
        ports:
            - 9002:9002
        volumes: 
            - ./business/app:/app
#        command: 
#            java -jar /app/expshare-business.jar --spring.profiles.active=prod && tail -f /etc/profile
        privileged: true
        depends_on: 
            - eureka

