version: '3'
services:
    mongo:
            image: mongo
            # restart: always
            ports: 
                - 27017:27017
            privileged: true
            tty: true
            volumes: 
                - ./mongo/data/db:/data/db
                # 初始化脚本，用来创建用户
                - ./mongo/data/scripts:/docker-entrypoint-initdb.d
            environment:
                MONGO_INITDB_ROOT_USERNAME: admin_username
                MONGO_INITDB_ROOT_PASSWORD: admin_password
            command: 
                mongod --replSet replicaSetForElasticsearch

    mongo-express:
            image: mongo-express
            # restart: always
            ports:
                - mongo_express_port:8081
            environment:
                ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_username
                ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_password
    redis:
            image: redis
            restart: always
            ports:
                - 6379:6379
            volumes: 
                - ./redis/data:/data
                - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
            tty: true
            privileged: true
            command: 
                redis-server /usr/local/etc/redis/redis.conf
    es: 
            image: elasticsearch
            ports: 
                - 9200:9200
                - 9300:9300
            volumes:
                - ./es/data:/usr/share/elasticsearch/data
                # ES需要宿主机而非docker容器的vm.max_map_count变量值至少为262144，编辑/etc/sysctl.conf,添加或修改vm.max_map_count=262144，
                # sysctl -p 使其生效 
                #- ./es/conf/sysctl.conf:/etc/sysctl.conf
                - ./es/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            tty: true
            privileged: true
            environment:
                # jvm内存配置，服务器内存不足可调整此参数    
                - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    mongoconnector:
            build: ./mongoconnector
            depends_on: 
                - es
                - mongo
            command: 
                mongo-connector -m mongo:27017 -t es:2900 -d elastic2_doc_manager
