spring:
  application:
    name: eureka-server

server:
  port: 9001

eureka:
  instance:
    hostname: eureka
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka:9001/eureka
